name: Metrics
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * MON'
  workflow_dispatch:
      inputs:
          description: {default: 'Start Metrics Workflow'}
          name: {default: 'Metrics for iwo-strzebonski'}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: iwo-strzebonski
          token: ${{ secrets.METRICS_TOKEN }} 
          template: classic
          base: header, activity, community, repositories, metadata

          config_timezone: Europe/Warsaw
          config_display: large

          repositories_forks: yes
          # repositories_affiliations: owner

          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          # plugin_skyline: yes
          # plugin_skyline_year: 2021
          # plugin_skyline_frames: 30
          # plugin_skyline_quality: 1
          # plugin_skyline_compatibility: yes

          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 5%
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_visibility: all

          plugin_repositories: yes
          plugin_repositories_forks: yes
          plugin_repositories_featured: iwo-strzebonski/ThaumicRevelations, iwo-strzebonski/WolfenScript3D, I-voR/SokobanThreeJS, I-voR/Sokobanbanban, iwo-strzebonski/WarhammerCalendar, iwo-strzebonski/RevasBot
          # plugin_repositories_affiliations: owner
          # plugin_repositories_batch: 100
          
          plugin_projects: yes
          plugin_projects_descriptions: yes
          plugin_projects_limit: 4

          plugin_lines: yes

          plugin_habits: yes
          plugin_habits_days: 360
          plugin_habits_facts: yes
          plugin_habits_from: 200

          # plugin_notable: yes
          # plugin_notable_from: all

          plugin_followup: yes
          plugin_followup_sections: repositories

          # plugin_pagespeed: yes
          # plugin_pagespeed_detailed: yes
          # plugin_pagespeed_url: https://octo-3d.herokuapp.com/

          # plugin_code: yes
          # plugin_code_lines: 12
          # plugin_code_load: 100
          # plugin_code_visibility: public

          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
