name: Metrics
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * MON'
  workflow_dispatch:
      inputs:
          description: {default: 'Start Metrics Workflow'}
          required: {required: true}
          name: {default: 'Metrics for iwo-strzebonski'}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: iwo-strzebonski
          token: ${{ secrets.METRICS_TOKEN }} 
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Warsaw
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_skyline: yes
          plugin_skyline_year: 0
          plugin_skyline_frames: 60
          plugin_skyline_quality: 0.5
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_visibility: all
          plugin_repositories: 100
          plugin_repositories_affiliations: owner
          plugin_repositories_batch: 100
          plugin_repositories_forks: yes
          repositories_forks: yes
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
